### ISSUE TITLE
Customize your college career 

### ISSUE THREAD

**Issue by bchanceylynn** [LynnUniversity/lynnedu#37]
- the where box doesn't allow you to choose an online program when you click on masters

- the entrepreneurial management degree is serving up the Program Group page instead of the program page. 

- We need to look back through these pages and check all instances to ensure content in being pushed properly.

**Comment by raptureaid** [comment]
The logic for the selection fields has been adjusted and code deployed. The other issues will be within the CMS - ensuring the keyword categories reference the degrees and not the group.

**Comment by bchanceylynn** [comment]
Looks good. I went through and checked all of the degrees. The only thing I noticed: the aviation certificates aren't showing up at all.

**Comment by raptureaid** [comment]
Aviation certs. need to be added within the CMS under the degree search keywords. Once added, this ticket can be closed.

**Comment by bchanceylynn** [comment]
These have been added.
