### ISSUE TITLE
Main navigation primary icon

### ISSUE THREAD

**Issue by raptureaid** [LynnUniversity/lynnedu#63]
The Main Navigation Primary shows a +/- icon when no children are available.

**Comment by jmcgaha** [comment]
Estimate: 1 hour

**Comment by jmcgaha** [comment]
Fixed on staging.
Couldn't find any instances of this occurring, maybe the nav has been simplified since the bug was filed. Regardless a conditional was added to only show the +/- if there are children of that nav item.

**Comment by raptureaid** [comment]
Correct, we altered the menu to prevent the bug from showing. This is verified as fixed and can be moved to production.
