### ISSUE TITLE
Fly-out close click target

### ISSUE THREAD

**Issue by raptureaid** [LynnUniversity/lynnedu#78]
When the fly-out (slide-out) container is open, allow areas outside of the container to act as a click target to close the window. The mouse pointer should display a large 'X' when over this area.

**Comment by jmcgaha** [comment]
Estimate: 2 hours

**Comment by jmcgaha** [comment]
Done on staging.

**Comment by jmcgaha** [comment]
Also changed gulp setup to minify the js. File went from over 650k to under 250k.

**Comment by raptureaid** [comment]
Can we change the mouse cursor when outside the open container?
