### ISSUE TITLE
Option to autoplay videos in a popup modal once opened.

### ISSUE THREAD

**Issue by raptureaid** [LynnUniversity/lynnedu#87]
The YouTube API allows videos to be set to autoplay, but this was being triggered during pageload. We need to delay the autoplay trigger event until the modal is opened.

Perhaps even delay loading the entire video object until the user makes the request to open the modal...

**Comment by jmcgaha** [comment]
Do you have a link where this occurs? Having trouble trying to find videos that aren't in the hero or just an iframe embedded in an article.

**Comment by raptureaid** [comment]
See the homepage on staging - first testimonial.

This is still using the old sliding container video embed field (rather than an entries field pulling in a video from those available in the YouTube entries section), but same concept. If autoplay is enabled, the video plays on page load - not when the modal is opened. If autoplay if off, two clicks are required to play the video - one to open the modal and another to start the video.

**Comment by raptureaid** [comment]
This is working in the updated testimonial pop-ups. Can be migrated to other pop-ups as needed.
